gateways:
    local:
        connection:
            type: duckdb
            database: db.db
    snowflake_db:
        connection:
            type: snowflake
            user: ${{vars.user}}
            password: ${{vars.password}}
            account: cy01830.eu-west-2.aws
            database: SQL_MESH_TEST
            warehouse: COMPUTE_WH
            role: ACCOUNTADMIN

model_defaults:
    dialect: snowflake

default_gateway: snowflake_db

cicd_bot:
    type: github
    merge_method: squash
    enable_deploy_command: true


    
